from redis

copy redis.conf /redis/redis.conf

Run chmod 777 /redis/redis.conf

expose 6379

cmd ["redis-server","/redis/redis.conf"]                                                                   
