"""empty message

Revision ID: 99305a316b73
Revises: 
Create Date: 2023-06-03 17:53:54.410688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99305a316b73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_user',
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('login_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.Date(), nullable=True),
    sa.Column('update_time', sa.Date(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friend_model',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('friend_id', sa.Integer(), nullable=True),
    sa.Column('apply_note', sa.String(length=100), nullable=True, comment='申请留言'),
    sa.Column('apply_status', sa.SmallInteger(), nullable=True),
    sa.Column('remark', sa.String(length=126), nullable=True),
    sa.Column('top', sa.SmallInteger(), nullable=True),
    sa.Column('black', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.Date(), nullable=True),
    sa.Column('update_time', sa.Date(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['t_user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('info_model',
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('mobile', sa.String(length=11), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('t_friend_chat_record',
    sa.Column('sender_id', sa.Integer(), nullable=True, comment='发送方'),
    sa.Column('receiver_id', sa.Integer(), nullable=True, comment='接受方'),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.Date(), nullable=True),
    sa.Column('update_time', sa.Date(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['t_user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_group',
    sa.Column('name', sa.String(length=64), nullable=True, comment='群名'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='群头像'),
    sa.Column('desc', sa.String(length=512), nullable=True, comment='简介'),
    sa.Column('member_count', sa.Integer(), nullable=True, comment='当前人数'),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('adminer_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.Date(), nullable=True),
    sa.Column('update_time', sa.Date(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['adminer_id'], ['t_user.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_group_apply',
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('apply_note', sa.String(length=100), nullable=True, comment='留言'),
    sa.Column('apply_status', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.Date(), nullable=True),
    sa.Column('update_time', sa.Date(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['t_group.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_group_chat_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True, comment='发送方'),
    sa.Column('group_id', sa.Integer(), nullable=True, comment='接受方'),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('create_time', sa.Date(), nullable=True),
    sa.Column('update_time', sa.Date(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['t_group.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['t_group_chat_record.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_group_mapping',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('join_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['t_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_group_mapping')
    op.drop_table('t_group_chat_record')
    op.drop_table('t_group_apply')
    op.drop_table('t_group')
    op.drop_table('t_friend_chat_record')
    op.drop_table('info_model')
    op.drop_table('friend_model')
    op.drop_table('t_user')
    # ### end Alembic commands ###
