
FROM minio/minio

ENV MINIO_ACCESS_KEY minioadmin
ENV MINIO_SECRET_KEY minioadmin
# docker run -p 9000:9000 -p 9090:9090 --name funchat_backend_minio -dit --restart=always -v ~/funchat-data/minio/data:/data funchat_backend_minio server /data --console-address ":9090" -address ":9000"