"""db default record

Revision ID: 2c81b7db3682
Revises: 
Create Date: 2023-07-26 20:50:44.251460

"""
from alembic import op
import sqlalchemy as sa
from app.db_default import db_init

# revision identifiers, used by Alembic.
revision = '2c81b7db3682'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'global_setting',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('top', sa.Integer(), nullable=True, comment='置顶'),
        sa.Column('remark', sa.String(length=50), nullable=True, comment='备注'),
        sa.Column('mute', sa.Integer(), nullable=True, comment='免打扰'),
        sa.Column('hide', sa.Integer(), nullable=True, comment='隐藏会话'),
        sa.Column('background', sa.String(length=255), nullable=True, comment='聊天背景'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'tag',
        sa.Column('name', sa.String(length=30), nullable=True),
        sa.Column('color', sa.String(length=30), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('create_time', sa.BigInteger(), nullable=True),
        sa.Column('update_time', sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'user',
        sa.Column('username', sa.String(length=64), nullable=True),
        sa.Column('password', sa.String(length=128), nullable=True, comment='密码'),
        sa.Column('last_login_time', sa.BigInteger(), nullable=True, comment='登录时间'),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('create_time', sa.BigInteger(), nullable=True),
        sa.Column('update_time', sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'friend',
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('friend_id', sa.Integer(), nullable=True),
        sa.Column('setting_id', sa.Integer(), nullable=True),
        sa.Column('favorite', sa.Integer(), nullable=True, comment='特别关心'),
        sa.Column('block', sa.Integer(), nullable=True, comment='拉黑'),
        sa.Column('type', sa.Integer(), nullable=True, comment='好友来源'),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('create_time', sa.BigInteger(), nullable=True),
        sa.Column('update_time', sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ['friend_id'],
            ['user.id'],
        ),
        sa.ForeignKeyConstraint(
            ['setting_id'],
            ['global_setting.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'group',
        sa.Column('name', sa.String(length=20), nullable=True),
        sa.Column('count', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('create_time', sa.BigInteger(), nullable=True),
        sa.Column('update_time', sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'group_chat',
        sa.Column('name', sa.String(length=64), nullable=True, comment='群名'),
        sa.Column('avatar', sa.String(length=255), nullable=True, comment='群头像'),
        sa.Column('description', sa.String(length=512), nullable=True, comment='简介'),
        sa.Column('member_count', sa.Integer(), nullable=True, comment='当前人数'),
        sa.Column('setting_id', sa.Integer(), nullable=True),
        sa.Column('owner_id', sa.Integer(), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('create_time', sa.BigInteger(), nullable=True),
        sa.Column('update_time', sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ['owner_id'],
            ['user.id'],
        ),
        sa.ForeignKeyConstraint(
            ['setting_id'],
            ['global_setting.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'information',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nickname', sa.String(length=64), nullable=True),
        sa.Column('avatar', sa.String(length=500), nullable=True, comment='用户头像图片'),
        sa.Column('gender', sa.Integer(), nullable=True, comment='用户性别'),
        sa.Column('mobile', sa.String(length=11), nullable=True, comment='电话号码'),
        sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
        sa.Column('note', sa.String(length=500), nullable=True, comment='个性签名'),
        sa.Column('birthday', sa.String(length=30), nullable=True),
        sa.Column('company', sa.String(length=30), nullable=True),
        sa.Column('address', sa.String(length=30), nullable=True),
        sa.Column('hometown', sa.String(length=30), nullable=True),
        sa.ForeignKeyConstraint(
            ['id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'user_tag_mapping',
        sa.Column('tag_id', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('liked_by_id', sa.Integer(), nullable=True),
        sa.Column('images', sa.String(length=255), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('create_time', sa.BigInteger(), nullable=True),
        sa.Column('update_time', sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ['liked_by_id'],
            ['user.id'],
        ),
        sa.ForeignKeyConstraint(
            ['tag_id'],
            ['tag.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'group_apply',
        sa.Column('sender_id', sa.Integer(), nullable=True),
        sa.Column('group_id', sa.Integer(), nullable=True),
        sa.Column('type', sa.Integer(), nullable=True, comment='好友来源'),
        sa.Column('apply_note', sa.String(length=100), nullable=True, comment='留言'),
        sa.Column('apply_status', sa.SmallInteger(), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('create_time', sa.BigInteger(), nullable=True),
        sa.Column('update_time', sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ['group_id'],
            ['group_chat.id'],
        ),
        sa.ForeignKeyConstraint(
            ['sender_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'group_chat_record',
        sa.Column('sender_id', sa.Integer(), nullable=True, comment='发送方'),
        sa.Column('group_chat_id', sa.Integer(), nullable=True, comment='接受方'),
        sa.Column('content', sa.String(length=500), nullable=False),
        sa.Column('read', sa.Integer(), nullable=True),
        sa.Column('is_reply', sa.Integer(), nullable=True),
        sa.Column('reply_id', sa.Integer(), nullable=True, comment='回复消息'),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('create_time', sa.BigInteger(), nullable=True),
        sa.Column('update_time', sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ['group_chat_id'],
            ['group_chat.id'],
        ),
        sa.ForeignKeyConstraint(
            ['reply_id'],
            ['group_chat_record.id'],
        ),
        sa.ForeignKeyConstraint(
            ['sender_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'user_group_mapping',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=False),
        sa.Column('role', sa.Integer(), nullable=True),
        sa.Column('join_time', sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ['group_id'],
            ['group_chat.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('user_id', 'group_id'),
    )
    # ### end Alembic commands ###
    db_init()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_group_mapping')
    op.drop_table('group_chat_record')
    op.drop_table('group_apply')
    op.drop_table('user_tag_mapping')
    op.drop_table('information')
    op.drop_table('group_chat')
    op.drop_table('group')
    op.drop_table('friend')
    op.drop_table('user')
    op.drop_table('tag')
    op.drop_table('global_setting')
    # ### end Alembic commands ###
