"""empty message

Revision ID: 799df4ffc52a
Revises: 
Create Date: 2023-07-23 22:19:52.430585

"""
from alembic import op
import sqlalchemy as sa
from passlib.handlers.pbkdf2 import pbkdf2_sha256

# revision identifiers, used by Alembic.
revision = '799df4ffc52a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tag_mapping',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('liked_by_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.BigInteger(), nullable=True),
    sa.Column('update_time', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['liked_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'user_id')
    )
    op.create_table('group_apply',
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True, comment='好友来源'),
    sa.Column('apply_note', sa.String(length=100), nullable=True, comment='留言'),
    sa.Column('apply_status', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.BigInteger(), nullable=True),
    sa.Column('update_time', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group_chat.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_chat_record',
    sa.Column('sender_id', sa.Integer(), nullable=True, comment='发送方'),
    sa.Column('group_chat_id', sa.Integer(), nullable=True, comment='接受方'),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('read', sa.Integer(), nullable=True),
    sa.Column('is_reply', sa.Integer(), nullable=True),
    sa.Column('reply_id', sa.Integer(), nullable=True, comment='回复消息'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.BigInteger(), nullable=True),
    sa.Column('update_time', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['group_chat_id'], ['group_chat.id'], ),
    sa.ForeignKeyConstraint(['reply_id'], ['group_chat_record.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_group_mapping',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('join_time', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group_chat.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_group_mapping')
    op.drop_table('group_chat_record')
    op.drop_table('group_apply')
    op.drop_table('user_tag_mapping')
    # ### end Alembic commands ###

# def default():
#     op.bulk_insert("user",[{"id":-1,"username":"admin","password":pbkdf2_sha256.hash("123456")}])