"""empty message

Revision ID: fed6da5a11e4
Revises: 99305a316b73
Create Date: 2023-06-04 15:05:58.183211

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fed6da5a11e4'
down_revision = '99305a316b73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_friend',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('friend_id', sa.Integer(), nullable=True),
    sa.Column('apply_note', sa.String(length=100), nullable=True, comment='申请留言'),
    sa.Column('apply_status', sa.SmallInteger(), nullable=True),
    sa.Column('remark', sa.String(length=126), nullable=True),
    sa.Column('top', sa.SmallInteger(), nullable=True),
    sa.Column('black', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.Date(), nullable=True),
    sa.Column('update_time', sa.Date(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['t_user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_info',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('mobile', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_table('friend_model')
    op.drop_table('info_model')
    with op.batch_alter_table('t_group', schema=None) as batch_op:
        batch_op.drop_constraint('t_group_ibfk_1', type_='foreignkey')
        batch_op.drop_column('adminer_id')

    with op.batch_alter_table('t_group_chat_record', schema=None) as batch_op:
        batch_op.alter_column('parent_id',
               existing_type=mysql.INTEGER(),
               comment='回复消息ID',
               existing_nullable=True)

    with op.batch_alter_table('user_group_mapping', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Integer(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('group_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_group_mapping', schema=None) as batch_op:
        batch_op.alter_column('group_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('role')

    with op.batch_alter_table('t_group_chat_record', schema=None) as batch_op:
        batch_op.alter_column('parent_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='回复消息ID',
               existing_nullable=True)

    with op.batch_alter_table('t_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adminer_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('t_group_ibfk_1', 't_user', ['adminer_id'], ['id'])

    op.create_table('info_model',
    sa.Column('nickname', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('avatar', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('gender', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('note', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('mobile', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.id'], name='info_model_ibfk_1'),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('friend_model',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('friend_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('apply_note', mysql.VARCHAR(length=100), nullable=True, comment='申请留言'),
    sa.Column('apply_status', mysql.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('remark', mysql.VARCHAR(length=126), nullable=True),
    sa.Column('top', mysql.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('black', mysql.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DATE(), nullable=True),
    sa.Column('update_time', sa.DATE(), nullable=True),
    sa.Column('status', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['t_user.id'], name='friend_model_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.id'], name='friend_model_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('t_info')
    op.drop_table('t_friend')
    # ### end Alembic commands ###
